// ============================================================================
// AUTO-GENERATED API CONTRACT TYPES
// Generated by @aibl-author/generator: `npm run dev:generator -- generate-api-types`
// DO NOT EDIT MANUALLY - Run the generator command to update
// ============================================================================

import type { inferRouterInputs, inferRouterOutputs } from "@trpc/server";
import type { AppRouter } from "@aibl-author/api";

export type RouterInputs = inferRouterInputs<AppRouter>;
export type RouterOutputs = inferRouterOutputs<AppRouter>;

// Helper types to extract item types from arrays or paginated envelopes
export type ExtractItem<T> = T extends (infer U)[]
  ? U
  : T extends { items: (infer U)[] }
  ? U
  : never;

export type ExtractArrayItem<T> = T extends (infer U)[] ? U : never;
export type ExtractPaginatedItem<T> = T extends { items: (infer U)[] } ? U : never;

// ----------------------------------------------------------------------------
// 📦 Router: agent
// ----------------------------------------------------------------------------
export type AgentCreateInput = RouterInputs["agent"]["create"];
export type AgentCreateOutput = RouterOutputs["agent"]["create"];
export type AgentCreateItem = ExtractItem<AgentCreateOutput>;

export type AgentGetInput = RouterInputs["agent"]["get"];
export type AgentGetOutput = RouterOutputs["agent"]["get"];
export type AgentGetItem = ExtractItem<AgentGetOutput>;

export type AgentListByOrganizationInput = RouterInputs["agent"]["listByOrganization"];
export type AgentListByOrganizationOutput = RouterOutputs["agent"]["listByOrganization"];
export type AgentListByOrganizationItem = ExtractItem<AgentListByOrganizationOutput>;

export type AgentListBySiteInput = RouterInputs["agent"]["listBySite"];
export type AgentListBySiteOutput = RouterOutputs["agent"]["listBySite"];
export type AgentListBySiteItem = ExtractItem<AgentListBySiteOutput>;

export type AgentListAccessibleInput = RouterInputs["agent"]["listAccessible"];
export type AgentListAccessibleOutput = RouterOutputs["agent"]["listAccessible"];
export type AgentListAccessibleItem = ExtractItem<AgentListAccessibleOutput>;

export type AgentCreateDraftInput = RouterInputs["agent"]["createDraft"];
export type AgentCreateDraftOutput = RouterOutputs["agent"]["createDraft"];
export type AgentCreateDraftItem = ExtractItem<AgentCreateDraftOutput>;

export type AgentUpdateDraftInput = RouterInputs["agent"]["updateDraft"];
export type AgentUpdateDraftOutput = RouterOutputs["agent"]["updateDraft"];
export type AgentUpdateDraftItem = ExtractItem<AgentUpdateDraftOutput>;

export type AgentGetVersionHistoryInput = RouterInputs["agent"]["getVersionHistory"];
export type AgentGetVersionHistoryOutput = RouterOutputs["agent"]["getVersionHistory"];
export type AgentGetVersionHistoryItem = ExtractItem<AgentGetVersionHistoryOutput>;

export type AgentSubmitForReviewInput = RouterInputs["agent"]["submitForReview"];
export type AgentSubmitForReviewOutput = RouterOutputs["agent"]["submitForReview"];
export type AgentSubmitForReviewItem = ExtractItem<AgentSubmitForReviewOutput>;

export type AgentAttachKnowledgeSourceInput = RouterInputs["agent"]["attachKnowledgeSource"];
export type AgentAttachKnowledgeSourceOutput = RouterOutputs["agent"]["attachKnowledgeSource"];
export type AgentAttachKnowledgeSourceItem = ExtractItem<AgentAttachKnowledgeSourceOutput>;

export type AgentRemoveKnowledgeSourceInput = RouterInputs["agent"]["removeKnowledgeSource"];
export type AgentRemoveKnowledgeSourceOutput = RouterOutputs["agent"]["removeKnowledgeSource"];
export type AgentRemoveKnowledgeSourceItem = ExtractItem<AgentRemoveKnowledgeSourceOutput>;

export type AgentStartChatSessionInput = RouterInputs["agent"]["startChatSession"];
export type AgentStartChatSessionOutput = RouterOutputs["agent"]["startChatSession"];
export type AgentStartChatSessionItem = ExtractItem<AgentStartChatSessionOutput>;

export type AgentSendMessageInput = RouterInputs["agent"]["sendMessage"];
export type AgentSendMessageOutput = RouterOutputs["agent"]["sendMessage"];
export type AgentSendMessageItem = ExtractItem<AgentSendMessageOutput>;

export type AgentDiscardDraftInput = RouterInputs["agent"]["discardDraft"];
export type AgentDiscardDraftOutput = RouterOutputs["agent"]["discardDraft"];
export type AgentDiscardDraftItem = ExtractItem<AgentDiscardDraftOutput>;

export type AgentListPendingInvitationsInput = RouterInputs["agent"]["listPendingInvitations"];
export type AgentListPendingInvitationsOutput = RouterOutputs["agent"]["listPendingInvitations"];
export type AgentListPendingInvitationsItem = ExtractItem<AgentListPendingInvitationsOutput>;

export type AgentAcceptInvitationInput = RouterInputs["agent"]["acceptInvitation"];
export type AgentAcceptInvitationOutput = RouterOutputs["agent"]["acceptInvitation"];
export type AgentAcceptInvitationItem = ExtractItem<AgentAcceptInvitationOutput>;

export type AgentDeclineInvitationInput = RouterInputs["agent"]["declineInvitation"];
export type AgentDeclineInvitationOutput = RouterOutputs["agent"]["declineInvitation"];
export type AgentDeclineInvitationItem = ExtractItem<AgentDeclineInvitationOutput>;

export type AgentDeleteInput = RouterInputs["agent"]["delete"];
export type AgentDeleteOutput = RouterOutputs["agent"]["delete"];
export type AgentDeleteItem = ExtractItem<AgentDeleteOutput>;

export type AgentAddAgentDelegationInput = RouterInputs["agent"]["addAgentDelegation"];
export type AgentAddAgentDelegationOutput = RouterOutputs["agent"]["addAgentDelegation"];
export type AgentAddAgentDelegationItem = ExtractItem<AgentAddAgentDelegationOutput>;

export type AgentRemoveAgentDelegationInput = RouterInputs["agent"]["removeAgentDelegation"];
export type AgentRemoveAgentDelegationOutput = RouterOutputs["agent"]["removeAgentDelegation"];
export type AgentRemoveAgentDelegationItem = ExtractItem<AgentRemoveAgentDelegationOutput>;

export type AgentListEligibleSubAgentsInput = RouterInputs["agent"]["listEligibleSubAgents"];
export type AgentListEligibleSubAgentsOutput = RouterOutputs["agent"]["listEligibleSubAgents"];
export type AgentListEligibleSubAgentsItem = ExtractItem<AgentListEligibleSubAgentsOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: agent.install
// ----------------------------------------------------------------------------
export type AgentInstallDelegateTiersInput = RouterInputs["agent"]["install"]["delegateTiers"];
export type AgentInstallDelegateTiersOutput = RouterOutputs["agent"]["install"]["delegateTiers"];
export type AgentInstallDelegateTiersItem = ExtractItem<AgentInstallDelegateTiersOutput>;

export type AgentInstallGetEffectivePermissionsInput = RouterInputs["agent"]["install"]["getEffectivePermissions"];
export type AgentInstallGetEffectivePermissionsOutput = RouterOutputs["agent"]["install"]["getEffectivePermissions"];
export type AgentInstallGetEffectivePermissionsItem = ExtractItem<AgentInstallGetEffectivePermissionsOutput>;

export type AgentInstallListInput = RouterInputs["agent"]["install"]["list"];
export type AgentInstallListOutput = RouterOutputs["agent"]["install"]["list"];
export type AgentInstallListItem = ExtractItem<AgentInstallListOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: chat
// ----------------------------------------------------------------------------
export type ChatChatStreamInput = RouterInputs["chat"]["chatStream"];
export type ChatChatStreamOutput = RouterOutputs["chat"]["chatStream"];
export type ChatChatStreamItem = ExtractItem<ChatChatStreamOutput>;

export type ChatGetChatSessionsInput = RouterInputs["chat"]["getChatSessions"];
export type ChatGetChatSessionsOutput = RouterOutputs["chat"]["getChatSessions"];
export type ChatGetChatSessionsItem = ExtractItem<ChatGetChatSessionsOutput>;

export type ChatGetChatMessagesInput = RouterInputs["chat"]["getChatMessages"];
export type ChatGetChatMessagesOutput = RouterOutputs["chat"]["getChatMessages"];
export type ChatGetChatMessagesItem = ExtractItem<ChatGetChatMessagesOutput>;

export type ChatDeleteChatSessionInput = RouterInputs["chat"]["deleteChatSession"];
export type ChatDeleteChatSessionOutput = RouterOutputs["chat"]["deleteChatSession"];
export type ChatDeleteChatSessionItem = ExtractItem<ChatDeleteChatSessionOutput>;

export type ChatRenameChatSessionInput = RouterInputs["chat"]["renameChatSession"];
export type ChatRenameChatSessionOutput = RouterOutputs["chat"]["renameChatSession"];
export type ChatRenameChatSessionItem = ExtractItem<ChatRenameChatSessionOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: health
// ----------------------------------------------------------------------------
export type HealthHelloInput = RouterInputs["health"]["hello"];
export type HealthHelloOutput = RouterOutputs["health"]["hello"];
export type HealthHelloItem = ExtractItem<HealthHelloOutput>;

export type HealthGetSecretMessageInput = RouterInputs["health"]["getSecretMessage"];
export type HealthGetSecretMessageOutput = RouterOutputs["health"]["getSecretMessage"];
export type HealthGetSecretMessageItem = ExtractItem<HealthGetSecretMessageOutput>;

export type HealthRefreshDevTokenInput = RouterInputs["health"]["refreshDevToken"];
export type HealthRefreshDevTokenOutput = RouterOutputs["health"]["refreshDevToken"];
export type HealthRefreshDevTokenItem = ExtractItem<HealthRefreshDevTokenOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: site
// ----------------------------------------------------------------------------
export type SiteAcceptInvitationInput = RouterInputs["site"]["acceptInvitation"];
export type SiteAcceptInvitationOutput = RouterOutputs["site"]["acceptInvitation"];
export type SiteAcceptInvitationItem = ExtractItem<SiteAcceptInvitationOutput>;

export type SiteCheckSlugAvailabilityInput = RouterInputs["site"]["checkSlugAvailability"];
export type SiteCheckSlugAvailabilityOutput = RouterOutputs["site"]["checkSlugAvailability"];
export type SiteCheckSlugAvailabilityItem = ExtractItem<SiteCheckSlugAvailabilityOutput>;

export type SiteCreateSiteInput = RouterInputs["site"]["createSite"];
export type SiteCreateSiteOutput = RouterOutputs["site"]["createSite"];
export type SiteCreateSiteItem = ExtractItem<SiteCreateSiteOutput>;

export type SiteCreateTierInput = RouterInputs["site"]["createTier"];
export type SiteCreateTierOutput = RouterOutputs["site"]["createTier"];
export type SiteCreateTierItem = ExtractItem<SiteCreateTierOutput>;

export type SiteDeleteTierInput = RouterInputs["site"]["deleteTier"];
export type SiteDeleteTierOutput = RouterOutputs["site"]["deleteTier"];
export type SiteDeleteTierItem = ExtractItem<SiteDeleteTierOutput>;

export type SiteGetBySlugInput = RouterInputs["site"]["getBySlug"];
export type SiteGetBySlugOutput = RouterOutputs["site"]["getBySlug"];
export type SiteGetBySlugItem = ExtractItem<SiteGetBySlugOutput>;

export type SiteGetReaderDataInput = RouterInputs["site"]["getReaderData"];
export type SiteGetReaderDataOutput = RouterOutputs["site"]["getReaderData"];
export type SiteGetReaderDataItem = ExtractItem<SiteGetReaderDataOutput>;

export type SiteInviteMemberInput = RouterInputs["site"]["inviteMember"];
export type SiteInviteMemberOutput = RouterOutputs["site"]["inviteMember"];
export type SiteInviteMemberItem = ExtractItem<SiteInviteMemberOutput>;

export type SiteListByOrganizationInput = RouterInputs["site"]["listByOrganization"];
export type SiteListByOrganizationOutput = RouterOutputs["site"]["listByOrganization"];
export type SiteListByOrganizationItem = ExtractItem<SiteListByOrganizationOutput>;

export type SiteListInvitationsInput = RouterInputs["site"]["listInvitations"];
export type SiteListInvitationsOutput = RouterOutputs["site"]["listInvitations"];
export type SiteListInvitationsItem = ExtractItem<SiteListInvitationsOutput>;

export type SiteListMembersInput = RouterInputs["site"]["listMembers"];
export type SiteListMembersOutput = RouterOutputs["site"]["listMembers"];
export type SiteListMembersItem = ExtractItem<SiteListMembersOutput>;

export type SiteListTiersInput = RouterInputs["site"]["listTiers"];
export type SiteListTiersOutput = RouterOutputs["site"]["listTiers"];
export type SiteListTiersItem = ExtractItem<SiteListTiersOutput>;

export type SiteRemoveMemberInput = RouterInputs["site"]["removeMember"];
export type SiteRemoveMemberOutput = RouterOutputs["site"]["removeMember"];
export type SiteRemoveMemberItem = ExtractItem<SiteRemoveMemberOutput>;

export type SiteUpdateMemberRolesInput = RouterInputs["site"]["updateMemberRoles"];
export type SiteUpdateMemberRolesOutput = RouterOutputs["site"]["updateMemberRoles"];
export type SiteUpdateMemberRolesItem = ExtractItem<SiteUpdateMemberRolesOutput>;

export type SiteUpdateMemberTierInput = RouterInputs["site"]["updateMemberTier"];
export type SiteUpdateMemberTierOutput = RouterOutputs["site"]["updateMemberTier"];
export type SiteUpdateMemberTierItem = ExtractItem<SiteUpdateMemberTierOutput>;

export type SiteUpdateTierInput = RouterInputs["site"]["updateTier"];
export type SiteUpdateTierOutput = RouterOutputs["site"]["updateTier"];
export type SiteUpdateTierItem = ExtractItem<SiteUpdateTierOutput>;

export type SiteUpdateMetadataInput = RouterInputs["site"]["updateMetadata"];
export type SiteUpdateMetadataOutput = RouterOutputs["site"]["updateMetadata"];
export type SiteUpdateMetadataItem = ExtractItem<SiteUpdateMetadataOutput>;

export type SiteProcessInvitationInput = RouterInputs["site"]["processInvitation"];
export type SiteProcessInvitationOutput = RouterOutputs["site"]["processInvitation"];
export type SiteProcessInvitationItem = ExtractItem<SiteProcessInvitationOutput>;

export type SiteListMyInvitationsInput = RouterInputs["site"]["listMyInvitations"];
export type SiteListMyInvitationsOutput = RouterOutputs["site"]["listMyInvitations"];
export type SiteListMyInvitationsItem = ExtractItem<SiteListMyInvitationsOutput>;

export type SiteUpdateAccessModeInput = RouterInputs["site"]["updateAccessMode"];
export type SiteUpdateAccessModeOutput = RouterOutputs["site"]["updateAccessMode"];
export type SiteUpdateAccessModeItem = ExtractItem<SiteUpdateAccessModeOutput>;

export type SiteDeleteSiteInput = RouterInputs["site"]["deleteSite"];
export type SiteDeleteSiteOutput = RouterOutputs["site"]["deleteSite"];
export type SiteDeleteSiteItem = ExtractItem<SiteDeleteSiteOutput>;

export type SiteListAccessibleInput = RouterInputs["site"]["listAccessible"];
export type SiteListAccessibleOutput = RouterOutputs["site"]["listAccessible"];
export type SiteListAccessibleItem = ExtractItem<SiteListAccessibleOutput>;

export type SiteInviteAgentInput = RouterInputs["site"]["inviteAgent"];
export type SiteInviteAgentOutput = RouterOutputs["site"]["inviteAgent"];
export type SiteInviteAgentItem = ExtractItem<SiteInviteAgentOutput>;

export type SiteListAgentsInput = RouterInputs["site"]["listAgents"];
export type SiteListAgentsOutput = RouterOutputs["site"]["listAgents"];
export type SiteListAgentsItem = ExtractItem<SiteListAgentsOutput>;

export type SiteListAuthorsInput = RouterInputs["site"]["listAuthors"];
export type SiteListAuthorsOutput = RouterOutputs["site"]["listAuthors"];
export type SiteListAuthorsItem = ExtractItem<SiteListAuthorsOutput>;

export type SiteUpdateAuthorProfileInput = RouterInputs["site"]["updateAuthorProfile"];
export type SiteUpdateAuthorProfileOutput = RouterOutputs["site"]["updateAuthorProfile"];
export type SiteUpdateAuthorProfileItem = ExtractItem<SiteUpdateAuthorProfileOutput>;

export type SiteGetReaderAuthorInput = RouterInputs["site"]["getReaderAuthor"];
export type SiteGetReaderAuthorOutput = RouterOutputs["site"]["getReaderAuthor"];
export type SiteGetReaderAuthorItem = ExtractItem<SiteGetReaderAuthorOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: system
// ----------------------------------------------------------------------------
export type SystemGetSystemStatusInput = RouterInputs["system"]["getSystemStatus"];
export type SystemGetSystemStatusOutput = RouterOutputs["system"]["getSystemStatus"];
export type SystemGetSystemStatusItem = ExtractItem<SystemGetSystemStatusOutput>;

export type SystemActivateOfflineInput = RouterInputs["system"]["activateOffline"];
export type SystemActivateOfflineOutput = RouterOutputs["system"]["activateOffline"];
export type SystemActivateOfflineItem = ExtractItem<SystemActivateOfflineOutput>;

export type SystemActivateOnlineInput = RouterInputs["system"]["activateOnline"];
export type SystemActivateOnlineOutput = RouterOutputs["system"]["activateOnline"];
export type SystemActivateOnlineItem = ExtractItem<SystemActivateOnlineOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: organizations
// ----------------------------------------------------------------------------
export type OrganizationsGetMyOrganizationsInput = RouterInputs["organizations"]["getMyOrganizations"];
export type OrganizationsGetMyOrganizationsOutput = RouterOutputs["organizations"]["getMyOrganizations"];
export type OrganizationsGetMyOrganizationsItem = ExtractItem<OrganizationsGetMyOrganizationsOutput>;

export type OrganizationsGetOrganizationBySlugOrIdInput = RouterInputs["organizations"]["getOrganizationBySlugOrId"];
export type OrganizationsGetOrganizationBySlugOrIdOutput = RouterOutputs["organizations"]["getOrganizationBySlugOrId"];
export type OrganizationsGetOrganizationBySlugOrIdItem = ExtractItem<OrganizationsGetOrganizationBySlugOrIdOutput>;

export type OrganizationsGetDirectoryInput = RouterInputs["organizations"]["getDirectory"];
export type OrganizationsGetDirectoryOutput = RouterOutputs["organizations"]["getDirectory"];
export type OrganizationsGetDirectoryItem = ExtractItem<OrganizationsGetDirectoryOutput>;

export type OrganizationsListMembersInput = RouterInputs["organizations"]["listMembers"];
export type OrganizationsListMembersOutput = RouterOutputs["organizations"]["listMembers"];
export type OrganizationsListMembersItem = ExtractItem<OrganizationsListMembersOutput>;

export type OrganizationsUpdateMemberRoleInput = RouterInputs["organizations"]["updateMemberRole"];
export type OrganizationsUpdateMemberRoleOutput = RouterOutputs["organizations"]["updateMemberRole"];
export type OrganizationsUpdateMemberRoleItem = ExtractItem<OrganizationsUpdateMemberRoleOutput>;

export type OrganizationsRemoveMemberInput = RouterInputs["organizations"]["removeMember"];
export type OrganizationsRemoveMemberOutput = RouterOutputs["organizations"]["removeMember"];
export type OrganizationsRemoveMemberItem = ExtractItem<OrganizationsRemoveMemberOutput>;

export type OrganizationsLeaveOrganizationInput = RouterInputs["organizations"]["leaveOrganization"];
export type OrganizationsLeaveOrganizationOutput = RouterOutputs["organizations"]["leaveOrganization"];
export type OrganizationsLeaveOrganizationItem = ExtractItem<OrganizationsLeaveOrganizationOutput>;

export type OrganizationsListInvitationsInput = RouterInputs["organizations"]["listInvitations"];
export type OrganizationsListInvitationsOutput = RouterOutputs["organizations"]["listInvitations"];
export type OrganizationsListInvitationsItem = ExtractItem<OrganizationsListInvitationsOutput>;

export type OrganizationsInviteMemberInput = RouterInputs["organizations"]["inviteMember"];
export type OrganizationsInviteMemberOutput = RouterOutputs["organizations"]["inviteMember"];
export type OrganizationsInviteMemberItem = ExtractItem<OrganizationsInviteMemberOutput>;

export type OrganizationsRevokeInvitationInput = RouterInputs["organizations"]["revokeInvitation"];
export type OrganizationsRevokeInvitationOutput = RouterOutputs["organizations"]["revokeInvitation"];
export type OrganizationsRevokeInvitationItem = ExtractItem<OrganizationsRevokeInvitationOutput>;

export type OrganizationsListMyInvitationsInput = RouterInputs["organizations"]["listMyInvitations"];
export type OrganizationsListMyInvitationsOutput = RouterOutputs["organizations"]["listMyInvitations"];
export type OrganizationsListMyInvitationsItem = ExtractItem<OrganizationsListMyInvitationsOutput>;

export type OrganizationsProcessInvitationInput = RouterInputs["organizations"]["processInvitation"];
export type OrganizationsProcessInvitationOutput = RouterOutputs["organizations"]["processInvitation"];
export type OrganizationsProcessInvitationItem = ExtractItem<OrganizationsProcessInvitationOutput>;

export type OrganizationsSubscribeToTierInput = RouterInputs["organizations"]["subscribeToTier"];
export type OrganizationsSubscribeToTierOutput = RouterOutputs["organizations"]["subscribeToTier"];
export type OrganizationsSubscribeToTierItem = ExtractItem<OrganizationsSubscribeToTierOutput>;

export type OrganizationsCreateInput = RouterInputs["organizations"]["create"];
export type OrganizationsCreateOutput = RouterOutputs["organizations"]["create"];
export type OrganizationsCreateItem = ExtractItem<OrganizationsCreateOutput>;

export type OrganizationsCheckSlugAvailabilityInput = RouterInputs["organizations"]["checkSlugAvailability"];
export type OrganizationsCheckSlugAvailabilityOutput = RouterOutputs["organizations"]["checkSlugAvailability"];
export type OrganizationsCheckSlugAvailabilityItem = ExtractItem<OrganizationsCheckSlugAvailabilityOutput>;

export type OrganizationsUpdateMetadataInput = RouterInputs["organizations"]["updateMetadata"];
export type OrganizationsUpdateMetadataOutput = RouterOutputs["organizations"]["updateMetadata"];
export type OrganizationsUpdateMetadataItem = ExtractItem<OrganizationsUpdateMetadataOutput>;

export type OrganizationsDeleteInput = RouterInputs["organizations"]["delete"];
export type OrganizationsDeleteOutput = RouterOutputs["organizations"]["delete"];
export type OrganizationsDeleteItem = ExtractItem<OrganizationsDeleteOutput>;

export type OrganizationsListReaderOrganizationsInput = RouterInputs["organizations"]["listReaderOrganizations"];
export type OrganizationsListReaderOrganizationsOutput = RouterOutputs["organizations"]["listReaderOrganizations"];
export type OrganizationsListReaderOrganizationsItem = ExtractItem<OrganizationsListReaderOrganizationsOutput>;

export type OrganizationsGetReaderOrganizationInput = RouterInputs["organizations"]["getReaderOrganization"];
export type OrganizationsGetReaderOrganizationOutput = RouterOutputs["organizations"]["getReaderOrganization"];
export type OrganizationsGetReaderOrganizationItem = ExtractItem<OrganizationsGetReaderOrganizationOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: organizations.llmConfig
// ----------------------------------------------------------------------------
export type OrganizationsLlmConfigCreateInput = RouterInputs["organizations"]["llmConfig"]["create"];
export type OrganizationsLlmConfigCreateOutput = RouterOutputs["organizations"]["llmConfig"]["create"];
export type OrganizationsLlmConfigCreateItem = ExtractItem<OrganizationsLlmConfigCreateOutput>;

export type OrganizationsLlmConfigUpdateInput = RouterInputs["organizations"]["llmConfig"]["update"];
export type OrganizationsLlmConfigUpdateOutput = RouterOutputs["organizations"]["llmConfig"]["update"];
export type OrganizationsLlmConfigUpdateItem = ExtractItem<OrganizationsLlmConfigUpdateOutput>;

export type OrganizationsLlmConfigListInput = RouterInputs["organizations"]["llmConfig"]["list"];
export type OrganizationsLlmConfigListOutput = RouterOutputs["organizations"]["llmConfig"]["list"];
export type OrganizationsLlmConfigListItem = ExtractItem<OrganizationsLlmConfigListOutput>;

export type OrganizationsLlmConfigPublishToMarketplaceInput = RouterInputs["organizations"]["llmConfig"]["publishToMarketplace"];
export type OrganizationsLlmConfigPublishToMarketplaceOutput = RouterOutputs["organizations"]["llmConfig"]["publishToMarketplace"];
export type OrganizationsLlmConfigPublishToMarketplaceItem = ExtractItem<OrganizationsLlmConfigPublishToMarketplaceOutput>;

export type OrganizationsLlmConfigUnpublishFromMarketplaceInput = RouterInputs["organizations"]["llmConfig"]["unpublishFromMarketplace"];
export type OrganizationsLlmConfigUnpublishFromMarketplaceOutput = RouterOutputs["organizations"]["llmConfig"]["unpublishFromMarketplace"];
export type OrganizationsLlmConfigUnpublishFromMarketplaceItem = ExtractItem<OrganizationsLlmConfigUnpublishFromMarketplaceOutput>;

export type OrganizationsLlmConfigInstallInput = RouterInputs["organizations"]["llmConfig"]["install"];
export type OrganizationsLlmConfigInstallOutput = RouterOutputs["organizations"]["llmConfig"]["install"];
export type OrganizationsLlmConfigInstallItem = ExtractItem<OrganizationsLlmConfigInstallOutput>;

export type OrganizationsLlmConfigUninstallInput = RouterInputs["organizations"]["llmConfig"]["uninstall"];
export type OrganizationsLlmConfigUninstallOutput = RouterOutputs["organizations"]["llmConfig"]["uninstall"];
export type OrganizationsLlmConfigUninstallItem = ExtractItem<OrganizationsLlmConfigUninstallOutput>;

export type OrganizationsLlmConfigDeleteInput = RouterInputs["organizations"]["llmConfig"]["delete"];
export type OrganizationsLlmConfigDeleteOutput = RouterOutputs["organizations"]["llmConfig"]["delete"];
export type OrganizationsLlmConfigDeleteItem = ExtractItem<OrganizationsLlmConfigDeleteOutput>;

export type OrganizationsLlmConfigListInstallationsInput = RouterInputs["organizations"]["llmConfig"]["listInstallations"];
export type OrganizationsLlmConfigListInstallationsOutput = RouterOutputs["organizations"]["llmConfig"]["listInstallations"];
export type OrganizationsLlmConfigListInstallationsItem = ExtractItem<OrganizationsLlmConfigListInstallationsOutput>;

export type OrganizationsLlmConfigListMarketplaceInput = RouterInputs["organizations"]["llmConfig"]["listMarketplace"];
export type OrganizationsLlmConfigListMarketplaceOutput = RouterOutputs["organizations"]["llmConfig"]["listMarketplace"];
export type OrganizationsLlmConfigListMarketplaceItem = ExtractItem<OrganizationsLlmConfigListMarketplaceOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: organizations.vectorStoreConfig
// ----------------------------------------------------------------------------
export type OrganizationsVectorStoreConfigCreateInput = RouterInputs["organizations"]["vectorStoreConfig"]["create"];
export type OrganizationsVectorStoreConfigCreateOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["create"];
export type OrganizationsVectorStoreConfigCreateItem = ExtractItem<OrganizationsVectorStoreConfigCreateOutput>;

export type OrganizationsVectorStoreConfigUpdateInput = RouterInputs["organizations"]["vectorStoreConfig"]["update"];
export type OrganizationsVectorStoreConfigUpdateOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["update"];
export type OrganizationsVectorStoreConfigUpdateItem = ExtractItem<OrganizationsVectorStoreConfigUpdateOutput>;

export type OrganizationsVectorStoreConfigListInput = RouterInputs["organizations"]["vectorStoreConfig"]["list"];
export type OrganizationsVectorStoreConfigListOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["list"];
export type OrganizationsVectorStoreConfigListItem = ExtractItem<OrganizationsVectorStoreConfigListOutput>;

export type OrganizationsVectorStoreConfigPublishToMarketplaceInput = RouterInputs["organizations"]["vectorStoreConfig"]["publishToMarketplace"];
export type OrganizationsVectorStoreConfigPublishToMarketplaceOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["publishToMarketplace"];
export type OrganizationsVectorStoreConfigPublishToMarketplaceItem = ExtractItem<OrganizationsVectorStoreConfigPublishToMarketplaceOutput>;

export type OrganizationsVectorStoreConfigUnpublishFromMarketplaceInput = RouterInputs["organizations"]["vectorStoreConfig"]["unpublishFromMarketplace"];
export type OrganizationsVectorStoreConfigUnpublishFromMarketplaceOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["unpublishFromMarketplace"];
export type OrganizationsVectorStoreConfigUnpublishFromMarketplaceItem = ExtractItem<OrganizationsVectorStoreConfigUnpublishFromMarketplaceOutput>;

export type OrganizationsVectorStoreConfigInstallInput = RouterInputs["organizations"]["vectorStoreConfig"]["install"];
export type OrganizationsVectorStoreConfigInstallOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["install"];
export type OrganizationsVectorStoreConfigInstallItem = ExtractItem<OrganizationsVectorStoreConfigInstallOutput>;

export type OrganizationsVectorStoreConfigUninstallInput = RouterInputs["organizations"]["vectorStoreConfig"]["uninstall"];
export type OrganizationsVectorStoreConfigUninstallOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["uninstall"];
export type OrganizationsVectorStoreConfigUninstallItem = ExtractItem<OrganizationsVectorStoreConfigUninstallOutput>;

export type OrganizationsVectorStoreConfigDeleteInput = RouterInputs["organizations"]["vectorStoreConfig"]["delete"];
export type OrganizationsVectorStoreConfigDeleteOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["delete"];
export type OrganizationsVectorStoreConfigDeleteItem = ExtractItem<OrganizationsVectorStoreConfigDeleteOutput>;

export type OrganizationsVectorStoreConfigListInstallationsInput = RouterInputs["organizations"]["vectorStoreConfig"]["listInstallations"];
export type OrganizationsVectorStoreConfigListInstallationsOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["listInstallations"];
export type OrganizationsVectorStoreConfigListInstallationsItem = ExtractItem<OrganizationsVectorStoreConfigListInstallationsOutput>;

export type OrganizationsVectorStoreConfigListMarketplaceInput = RouterInputs["organizations"]["vectorStoreConfig"]["listMarketplace"];
export type OrganizationsVectorStoreConfigListMarketplaceOutput = RouterOutputs["organizations"]["vectorStoreConfig"]["listMarketplace"];
export type OrganizationsVectorStoreConfigListMarketplaceItem = ExtractItem<OrganizationsVectorStoreConfigListMarketplaceOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: organizations.doclingServerConfig
// ----------------------------------------------------------------------------
export type OrganizationsDoclingServerConfigCreateInput = RouterInputs["organizations"]["doclingServerConfig"]["create"];
export type OrganizationsDoclingServerConfigCreateOutput = RouterOutputs["organizations"]["doclingServerConfig"]["create"];
export type OrganizationsDoclingServerConfigCreateItem = ExtractItem<OrganizationsDoclingServerConfigCreateOutput>;

export type OrganizationsDoclingServerConfigUpdateInput = RouterInputs["organizations"]["doclingServerConfig"]["update"];
export type OrganizationsDoclingServerConfigUpdateOutput = RouterOutputs["organizations"]["doclingServerConfig"]["update"];
export type OrganizationsDoclingServerConfigUpdateItem = ExtractItem<OrganizationsDoclingServerConfigUpdateOutput>;

export type OrganizationsDoclingServerConfigListInput = RouterInputs["organizations"]["doclingServerConfig"]["list"];
export type OrganizationsDoclingServerConfigListOutput = RouterOutputs["organizations"]["doclingServerConfig"]["list"];
export type OrganizationsDoclingServerConfigListItem = ExtractItem<OrganizationsDoclingServerConfigListOutput>;

export type OrganizationsDoclingServerConfigPublishToMarketplaceInput = RouterInputs["organizations"]["doclingServerConfig"]["publishToMarketplace"];
export type OrganizationsDoclingServerConfigPublishToMarketplaceOutput = RouterOutputs["organizations"]["doclingServerConfig"]["publishToMarketplace"];
export type OrganizationsDoclingServerConfigPublishToMarketplaceItem = ExtractItem<OrganizationsDoclingServerConfigPublishToMarketplaceOutput>;

export type OrganizationsDoclingServerConfigUnpublishFromMarketplaceInput = RouterInputs["organizations"]["doclingServerConfig"]["unpublishFromMarketplace"];
export type OrganizationsDoclingServerConfigUnpublishFromMarketplaceOutput = RouterOutputs["organizations"]["doclingServerConfig"]["unpublishFromMarketplace"];
export type OrganizationsDoclingServerConfigUnpublishFromMarketplaceItem = ExtractItem<OrganizationsDoclingServerConfigUnpublishFromMarketplaceOutput>;

export type OrganizationsDoclingServerConfigInstallInput = RouterInputs["organizations"]["doclingServerConfig"]["install"];
export type OrganizationsDoclingServerConfigInstallOutput = RouterOutputs["organizations"]["doclingServerConfig"]["install"];
export type OrganizationsDoclingServerConfigInstallItem = ExtractItem<OrganizationsDoclingServerConfigInstallOutput>;

export type OrganizationsDoclingServerConfigUninstallInput = RouterInputs["organizations"]["doclingServerConfig"]["uninstall"];
export type OrganizationsDoclingServerConfigUninstallOutput = RouterOutputs["organizations"]["doclingServerConfig"]["uninstall"];
export type OrganizationsDoclingServerConfigUninstallItem = ExtractItem<OrganizationsDoclingServerConfigUninstallOutput>;

export type OrganizationsDoclingServerConfigDeleteInput = RouterInputs["organizations"]["doclingServerConfig"]["delete"];
export type OrganizationsDoclingServerConfigDeleteOutput = RouterOutputs["organizations"]["doclingServerConfig"]["delete"];
export type OrganizationsDoclingServerConfigDeleteItem = ExtractItem<OrganizationsDoclingServerConfigDeleteOutput>;

export type OrganizationsDoclingServerConfigListInstallationsInput = RouterInputs["organizations"]["doclingServerConfig"]["listInstallations"];
export type OrganizationsDoclingServerConfigListInstallationsOutput = RouterOutputs["organizations"]["doclingServerConfig"]["listInstallations"];
export type OrganizationsDoclingServerConfigListInstallationsItem = ExtractItem<OrganizationsDoclingServerConfigListInstallationsOutput>;

export type OrganizationsDoclingServerConfigListMarketplaceInput = RouterInputs["organizations"]["doclingServerConfig"]["listMarketplace"];
export type OrganizationsDoclingServerConfigListMarketplaceOutput = RouterOutputs["organizations"]["doclingServerConfig"]["listMarketplace"];
export type OrganizationsDoclingServerConfigListMarketplaceItem = ExtractItem<OrganizationsDoclingServerConfigListMarketplaceOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: iam
// ----------------------------------------------------------------------------
export type IamMeInput = RouterInputs["iam"]["me"];
export type IamMeOutput = RouterOutputs["iam"]["me"];
export type IamMeItem = ExtractItem<IamMeOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: workflow
// ----------------------------------------------------------------------------
export type WorkflowResolveEffectiveInput = RouterInputs["workflow"]["resolveEffective"];
export type WorkflowResolveEffectiveOutput = RouterOutputs["workflow"]["resolveEffective"];
export type WorkflowResolveEffectiveItem = ExtractItem<WorkflowResolveEffectiveOutput>;

export type WorkflowListEligibleParticipantsInput = RouterInputs["workflow"]["listEligibleParticipants"];
export type WorkflowListEligibleParticipantsOutput = RouterOutputs["workflow"]["listEligibleParticipants"];
export type WorkflowListEligibleParticipantsItem = ExtractItem<WorkflowListEligibleParticipantsOutput>;

export type WorkflowCreateDefinitionInput = RouterInputs["workflow"]["createDefinition"];
export type WorkflowCreateDefinitionOutput = RouterOutputs["workflow"]["createDefinition"];
export type WorkflowCreateDefinitionItem = ExtractItem<WorkflowCreateDefinitionOutput>;

export type WorkflowListDefinitionsInput = RouterInputs["workflow"]["listDefinitions"];
export type WorkflowListDefinitionsOutput = RouterOutputs["workflow"]["listDefinitions"];
export type WorkflowListDefinitionsItem = ExtractItem<WorkflowListDefinitionsOutput>;

export type WorkflowCreateVersionInput = RouterInputs["workflow"]["createVersion"];
export type WorkflowCreateVersionOutput = RouterOutputs["workflow"]["createVersion"];
export type WorkflowCreateVersionItem = ExtractItem<WorkflowCreateVersionOutput>;

export type WorkflowListVersionsInput = RouterInputs["workflow"]["listVersions"];
export type WorkflowListVersionsOutput = RouterOutputs["workflow"]["listVersions"];
export type WorkflowListVersionsItem = ExtractItem<WorkflowListVersionsOutput>;

export type WorkflowPublishVersionInput = RouterInputs["workflow"]["publishVersion"];
export type WorkflowPublishVersionOutput = RouterOutputs["workflow"]["publishVersion"];
export type WorkflowPublishVersionItem = ExtractItem<WorkflowPublishVersionOutput>;

export type WorkflowDeleteVersionInput = RouterInputs["workflow"]["deleteVersion"];
export type WorkflowDeleteVersionOutput = RouterOutputs["workflow"]["deleteVersion"];
export type WorkflowDeleteVersionItem = ExtractItem<WorkflowDeleteVersionOutput>;

export type WorkflowDeleteInactiveVersionsInput = RouterInputs["workflow"]["deleteInactiveVersions"];
export type WorkflowDeleteInactiveVersionsOutput = RouterOutputs["workflow"]["deleteInactiveVersions"];
export type WorkflowDeleteInactiveVersionsItem = ExtractItem<WorkflowDeleteInactiveVersionsOutput>;

export type WorkflowSetOrganizationDefaultInput = RouterInputs["workflow"]["setOrganizationDefault"];
export type WorkflowSetOrganizationDefaultOutput = RouterOutputs["workflow"]["setOrganizationDefault"];
export type WorkflowSetOrganizationDefaultItem = ExtractItem<WorkflowSetOrganizationDefaultOutput>;

export type WorkflowSetSiteDefaultInput = RouterInputs["workflow"]["setSiteDefault"];
export type WorkflowSetSiteDefaultOutput = RouterOutputs["workflow"]["setSiteDefault"];
export type WorkflowSetSiteDefaultItem = ExtractItem<WorkflowSetSiteDefaultOutput>;

export type WorkflowSetTierDefaultInput = RouterInputs["workflow"]["setTierDefault"];
export type WorkflowSetTierDefaultOutput = RouterOutputs["workflow"]["setTierDefault"];
export type WorkflowSetTierDefaultItem = ExtractItem<WorkflowSetTierDefaultOutput>;

export type WorkflowSubmitForReviewInput = RouterInputs["workflow"]["submitForReview"];
export type WorkflowSubmitForReviewOutput = RouterOutputs["workflow"]["submitForReview"];
export type WorkflowSubmitForReviewItem = ExtractItem<WorkflowSubmitForReviewOutput>;

export type WorkflowListPendingReviewsInput = RouterInputs["workflow"]["listPendingReviews"];
export type WorkflowListPendingReviewsOutput = RouterOutputs["workflow"]["listPendingReviews"];
export type WorkflowListPendingReviewsItem = ExtractItem<WorkflowListPendingReviewsOutput>;

export type WorkflowActOnReviewRequestInput = RouterInputs["workflow"]["actOnReviewRequest"];
export type WorkflowActOnReviewRequestOutput = RouterOutputs["workflow"]["actOnReviewRequest"];
export type WorkflowActOnReviewRequestItem = ExtractItem<WorkflowActOnReviewRequestOutput>;

export type WorkflowGetReviewRequestInput = RouterInputs["workflow"]["getReviewRequest"];
export type WorkflowGetReviewRequestOutput = RouterOutputs["workflow"]["getReviewRequest"];
export type WorkflowGetReviewRequestItem = ExtractItem<WorkflowGetReviewRequestOutput>;

export type WorkflowAddReviewCommentInput = RouterInputs["workflow"]["addReviewComment"];
export type WorkflowAddReviewCommentOutput = RouterOutputs["workflow"]["addReviewComment"];
export type WorkflowAddReviewCommentItem = ExtractItem<WorkflowAddReviewCommentOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: post
// ----------------------------------------------------------------------------
export type PostCreateInput = RouterInputs["post"]["create"];
export type PostCreateOutput = RouterOutputs["post"]["create"];
export type PostCreateItem = ExtractItem<PostCreateOutput>;

export type PostGetInput = RouterInputs["post"]["get"];
export type PostGetOutput = RouterOutputs["post"]["get"];
export type PostGetItem = ExtractItem<PostGetOutput>;

export type PostGetReaderDataInput = RouterInputs["post"]["getReaderData"];
export type PostGetReaderDataOutput = RouterOutputs["post"]["getReaderData"];
export type PostGetReaderDataItem = ExtractItem<PostGetReaderDataOutput>;

export type PostListBySiteInput = RouterInputs["post"]["listBySite"];
export type PostListBySiteOutput = RouterOutputs["post"]["listBySite"];
export type PostListBySiteItem = ExtractItem<PostListBySiteOutput>;

export type PostCreateDraftInput = RouterInputs["post"]["createDraft"];
export type PostCreateDraftOutput = RouterOutputs["post"]["createDraft"];
export type PostCreateDraftItem = ExtractItem<PostCreateDraftOutput>;

export type PostUpdateDraftInput = RouterInputs["post"]["updateDraft"];
export type PostUpdateDraftOutput = RouterOutputs["post"]["updateDraft"];
export type PostUpdateDraftItem = ExtractItem<PostUpdateDraftOutput>;

export type PostDiscardDraftInput = RouterInputs["post"]["discardDraft"];
export type PostDiscardDraftOutput = RouterOutputs["post"]["discardDraft"];
export type PostDiscardDraftItem = ExtractItem<PostDiscardDraftOutput>;

export type PostGetVersionHistoryInput = RouterInputs["post"]["getVersionHistory"];
export type PostGetVersionHistoryOutput = RouterOutputs["post"]["getVersionHistory"];
export type PostGetVersionHistoryItem = ExtractItem<PostGetVersionHistoryOutput>;

export type PostSubmitForReviewInput = RouterInputs["post"]["submitForReview"];
export type PostSubmitForReviewOutput = RouterOutputs["post"]["submitForReview"];
export type PostSubmitForReviewItem = ExtractItem<PostSubmitForReviewOutput>;

export type PostDeleteInput = RouterInputs["post"]["delete"];
export type PostDeleteOutput = RouterOutputs["post"]["delete"];
export type PostDeleteItem = ExtractItem<PostDeleteOutput>;

export type PostListBySitePaginatedInput = RouterInputs["post"]["listBySitePaginated"];
export type PostListBySitePaginatedOutput = RouterOutputs["post"]["listBySitePaginated"];
export type PostListBySitePaginatedItem = ExtractItem<PostListBySitePaginatedOutput>;

export type PostListReaderPostsInput = RouterInputs["post"]["listReaderPosts"];
export type PostListReaderPostsOutput = RouterOutputs["post"]["listReaderPosts"];
export type PostListReaderPostsItem = ExtractItem<PostListReaderPostsOutput>;

export type PostGetAnalyticsInput = RouterInputs["post"]["getAnalytics"];
export type PostGetAnalyticsOutput = RouterOutputs["post"]["getAnalytics"];
export type PostGetAnalyticsItem = ExtractItem<PostGetAnalyticsOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: taxonomy
// ----------------------------------------------------------------------------
export type TaxonomyGetCategoriesInput = RouterInputs["taxonomy"]["getCategories"];
export type TaxonomyGetCategoriesOutput = RouterOutputs["taxonomy"]["getCategories"];
export type TaxonomyGetCategoriesItem = ExtractItem<TaxonomyGetCategoriesOutput>;

export type TaxonomyGetTagsInput = RouterInputs["taxonomy"]["getTags"];
export type TaxonomyGetTagsOutput = RouterOutputs["taxonomy"]["getTags"];
export type TaxonomyGetTagsItem = ExtractItem<TaxonomyGetTagsOutput>;

export type TaxonomyUpsertCategoryInput = RouterInputs["taxonomy"]["upsertCategory"];
export type TaxonomyUpsertCategoryOutput = RouterOutputs["taxonomy"]["upsertCategory"];
export type TaxonomyUpsertCategoryItem = ExtractItem<TaxonomyUpsertCategoryOutput>;

export type TaxonomyUpsertTagInput = RouterInputs["taxonomy"]["upsertTag"];
export type TaxonomyUpsertTagOutput = RouterOutputs["taxonomy"]["upsertTag"];
export type TaxonomyUpsertTagItem = ExtractItem<TaxonomyUpsertTagOutput>;

export type TaxonomyDeleteCategoryInput = RouterInputs["taxonomy"]["deleteCategory"];
export type TaxonomyDeleteCategoryOutput = RouterOutputs["taxonomy"]["deleteCategory"];
export type TaxonomyDeleteCategoryItem = ExtractItem<TaxonomyDeleteCategoryOutput>;

export type TaxonomyDeleteTagInput = RouterInputs["taxonomy"]["deleteTag"];
export type TaxonomyDeleteTagOutput = RouterOutputs["taxonomy"]["deleteTag"];
export type TaxonomyDeleteTagItem = ExtractItem<TaxonomyDeleteTagOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: media
// ----------------------------------------------------------------------------
export type MediaUploadAssetInput = RouterInputs["media"]["uploadAsset"];
export type MediaUploadAssetOutput = RouterOutputs["media"]["uploadAsset"];
export type MediaUploadAssetItem = ExtractItem<MediaUploadAssetOutput>;

export type MediaListInput = RouterInputs["media"]["list"];
export type MediaListOutput = RouterOutputs["media"]["list"];
export type MediaListItem = ExtractItem<MediaListOutput>;

export type MediaDeleteInput = RouterInputs["media"]["delete"];
export type MediaDeleteOutput = RouterOutputs["media"]["delete"];
export type MediaDeleteItem = ExtractItem<MediaDeleteOutput>;

export type MediaChangeScopeInput = RouterInputs["media"]["changeScope"];
export type MediaChangeScopeOutput = RouterOutputs["media"]["changeScope"];
export type MediaChangeScopeItem = ExtractItem<MediaChangeScopeOutput>;

export type MediaGetInput = RouterInputs["media"]["get"];
export type MediaGetOutput = RouterOutputs["media"]["get"];
export type MediaGetItem = ExtractItem<MediaGetOutput>;

export type MediaRenameInput = RouterInputs["media"]["rename"];
export type MediaRenameOutput = RouterOutputs["media"]["rename"];
export type MediaRenameItem = ExtractItem<MediaRenameOutput>;

export type MediaRegenerateMetadataInput = RouterInputs["media"]["regenerateMetadata"];
export type MediaRegenerateMetadataOutput = RouterOutputs["media"]["regenerateMetadata"];
export type MediaRegenerateMetadataItem = ExtractItem<MediaRegenerateMetadataOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: marketplace
// ----------------------------------------------------------------------------
export type MarketplaceListInput = RouterInputs["marketplace"]["list"];
export type MarketplaceListOutput = RouterOutputs["marketplace"]["list"];
export type MarketplaceListItem = ExtractItem<MarketplaceListOutput>;

export type MarketplacePublishInput = RouterInputs["marketplace"]["publish"];
export type MarketplacePublishOutput = RouterOutputs["marketplace"]["publish"];
export type MarketplacePublishItem = ExtractItem<MarketplacePublishOutput>;

export type MarketplaceUnpublishInput = RouterInputs["marketplace"]["unpublish"];
export type MarketplaceUnpublishOutput = RouterOutputs["marketplace"]["unpublish"];
export type MarketplaceUnpublishItem = ExtractItem<MarketplaceUnpublishOutput>;

export type MarketplaceGetListingInput = RouterInputs["marketplace"]["getListing"];
export type MarketplaceGetListingOutput = RouterOutputs["marketplace"]["getListing"];
export type MarketplaceGetListingItem = ExtractItem<MarketplaceGetListingOutput>;

export type MarketplaceInstallAgentInput = RouterInputs["marketplace"]["installAgent"];
export type MarketplaceInstallAgentOutput = RouterOutputs["marketplace"]["installAgent"];
export type MarketplaceInstallAgentItem = ExtractItem<MarketplaceInstallAgentOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: search
// ----------------------------------------------------------------------------
export type SearchQueryInput = RouterInputs["search"]["query"];
export type SearchQueryOutput = RouterOutputs["search"]["query"];
export type SearchQueryItem = ExtractItem<SearchQueryOutput>;

export type SearchTrackSearchClickInput = RouterInputs["search"]["trackSearchClick"];
export type SearchTrackSearchClickOutput = RouterOutputs["search"]["trackSearchClick"];
export type SearchTrackSearchClickItem = ExtractItem<SearchTrackSearchClickOutput>;

export type SearchGlobalInput = RouterInputs["search"]["global"];
export type SearchGlobalOutput = RouterOutputs["search"]["global"];
export type SearchGlobalItem = ExtractItem<SearchGlobalOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: analytics
// ----------------------------------------------------------------------------
export type AnalyticsGetSiteOverviewInput = RouterInputs["analytics"]["getSiteOverview"];
export type AnalyticsGetSiteOverviewOutput = RouterOutputs["analytics"]["getSiteOverview"];
export type AnalyticsGetSiteOverviewItem = ExtractItem<AnalyticsGetSiteOverviewOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: notification
// ----------------------------------------------------------------------------
export type NotificationListMyNotificationsInput = RouterInputs["notification"]["listMyNotifications"];
export type NotificationListMyNotificationsOutput = RouterOutputs["notification"]["listMyNotifications"];
export type NotificationListMyNotificationsItem = ExtractItem<NotificationListMyNotificationsOutput>;

export type NotificationListMyTasksInput = RouterInputs["notification"]["listMyTasks"];
export type NotificationListMyTasksOutput = RouterOutputs["notification"]["listMyTasks"];
export type NotificationListMyTasksItem = ExtractItem<NotificationListMyTasksOutput>;

export type NotificationMarkReadInput = RouterInputs["notification"]["markRead"];
export type NotificationMarkReadOutput = RouterOutputs["notification"]["markRead"];
export type NotificationMarkReadItem = ExtractItem<NotificationMarkReadOutput>;

export type NotificationMarkAllReadInput = RouterInputs["notification"]["markAllRead"];
export type NotificationMarkAllReadOutput = RouterOutputs["notification"]["markAllRead"];
export type NotificationMarkAllReadItem = ExtractItem<NotificationMarkAllReadOutput>;

export type NotificationArchiveInput = RouterInputs["notification"]["archive"];
export type NotificationArchiveOutput = RouterOutputs["notification"]["archive"];
export type NotificationArchiveItem = ExtractItem<NotificationArchiveOutput>;

export type NotificationListInboxInput = RouterInputs["notification"]["listInbox"];
export type NotificationListInboxOutput = RouterOutputs["notification"]["listInbox"];
export type NotificationListInboxItem = ExtractItem<NotificationListInboxOutput>;

export type NotificationGetInboxCountsInput = RouterInputs["notification"]["getInboxCounts"];
export type NotificationGetInboxCountsOutput = RouterOutputs["notification"]["getInboxCounts"];
export type NotificationGetInboxCountsItem = ExtractItem<NotificationGetInboxCountsOutput>;

export type NotificationGetInboxFilterOptionsInput = RouterInputs["notification"]["getInboxFilterOptions"];
export type NotificationGetInboxFilterOptionsOutput = RouterOutputs["notification"]["getInboxFilterOptions"];
export type NotificationGetInboxFilterOptionsItem = ExtractItem<NotificationGetInboxFilterOptionsOutput>;

export type NotificationGetSiteWatchLevelInput = RouterInputs["notification"]["getSiteWatchLevel"];
export type NotificationGetSiteWatchLevelOutput = RouterOutputs["notification"]["getSiteWatchLevel"];
export type NotificationGetSiteWatchLevelItem = ExtractItem<NotificationGetSiteWatchLevelOutput>;

export type NotificationSetSiteWatchLevelInput = RouterInputs["notification"]["setSiteWatchLevel"];
export type NotificationSetSiteWatchLevelOutput = RouterOutputs["notification"]["setSiteWatchLevel"];
export type NotificationSetSiteWatchLevelItem = ExtractItem<NotificationSetSiteWatchLevelOutput>;

// ----------------------------------------------------------------------------
// 📦 Router: defaultInstalls
// ----------------------------------------------------------------------------
export type DefaultInstallsGetDefaultInstallsInput = RouterInputs["defaultInstalls"]["getDefaultInstalls"];
export type DefaultInstallsGetDefaultInstallsOutput = RouterOutputs["defaultInstalls"]["getDefaultInstalls"];
export type DefaultInstallsGetDefaultInstallsItem = ExtractItem<DefaultInstallsGetDefaultInstallsOutput>;

export type DefaultInstallsCreateDefaultInstallInput = RouterInputs["defaultInstalls"]["createDefaultInstall"];
export type DefaultInstallsCreateDefaultInstallOutput = RouterOutputs["defaultInstalls"]["createDefaultInstall"];
export type DefaultInstallsCreateDefaultInstallItem = ExtractItem<DefaultInstallsCreateDefaultInstallOutput>;

export type DefaultInstallsDeleteDefaultInstallInput = RouterInputs["defaultInstalls"]["deleteDefaultInstall"];
export type DefaultInstallsDeleteDefaultInstallOutput = RouterOutputs["defaultInstalls"]["deleteDefaultInstall"];
export type DefaultInstallsDeleteDefaultInstallItem = ExtractItem<DefaultInstallsDeleteDefaultInstallOutput>;

